#!/usr/bin/env bash


# Start of config
DATABASE=xoundboy_dev
DBUSER=root
DUMPFILE=xoundboy_dev.sql
DUMPFILENODATA=xoundboy_dev_no_data.sql
# End of config


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Dump the database with data
if [ "$1" == "dump" ]; then
    mysqldump -u${DBUSER} -p ${DATABASE} --routines > ${DIR}/sql/${DUMPFILE}

# Dump without data
elif [ "$1" == "dumpnodata" ]; then
    mysqldump -u${DBUSER} -p -d ${DATABASE} --routines >  ${DIR}/sql/${DUMPFILENODATA}

# Load database with data
elif [ "$1" == "load" ]; then
    mysql -u${DBUSER} -p ${DATABASE} < ${DIR}/sql/${DUMPFILE}

# Load without data (just schema)
elif [ "$1" == "loadnodata" ]; then
    mysql -u${DBUSER} -p ${DATABASE} < ${DIR}/sql/${DUMPFILENODATA}

# Show no arg error
else
    echo "no argument passed. Possible arg values..."
    echo "[dump|dumpnodata|load|loadnodata]"
fi