#!/usr/bin/env bash


# Start of config
DATABASE=   # database name
DBUSER=     # database user
DBPASS=     # database user's password
# End of config

DUMPFILE=x7db.sql
DUMPFILENODATA=x7db_no_data.sql

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Dump the database with data
if [ "$1" == "dump" ]; then
    mysqldump -u${DBUSER} -p${DBPASS} ${DATABASE} --routines > ${DIR}/sql/${DUMPFILE}

# Dump without data
elif [ "$1" == "dumpnodata" ]; then
    mysqldump -u${DBUSER} -p${DBPASS} -d ${DATABASE} --routines >  ${DIR}/sql/${DUMPFILENODATA}

# Load database with data
elif [ "$1" == "load" ]; then
    mysql -u${DBUSER} -p${DBPASS} ${DATABASE} < ${DIR}/sql/${DUMPFILE}

# Load without data (just schema)
elif [ "$1" == "loadnodata" ]; then
    mysql -u${DBUSER} -p${DBPASS} ${DATABASE} < ${DIR}/sql/${DUMPFILENODATA}

# Show no arg error
else
    echo "no argument passed. Possible arg values..."
    echo "[dump|dumpnodata|load|loadnodata]"
fi